"""Server field port key

Revision ID: 100e54d60d36
Revises: 3104a1bdfa3d
Create Date: 2024-08-03 15:28:55.782668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '100e54d60d36'
down_revision: Union[str, None] = '3104a1bdfa3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('server', sa.Column('port_key', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('server', 'port_key')
    # ### end Alembic commands ###
