"""Server fields

Revision ID: 3104a1bdfa3d
Revises: d848cef80bec
Create Date: 2024-08-03 15:17:59.461427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3104a1bdfa3d'
down_revision: Union[str, None] = 'd848cef80bec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('server', sa.Column('short_id', sa.String(length=10), nullable=True))
    op.add_column('server', sa.Column('public_key', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('server', 'public_key')
    op.drop_column('server', 'short_id')
    # ### end Alembic commands ###
